import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, Menu, Plus, X } from 'lucide-react';
import './fashion-experience.css';

const root = '/assets/thoi-trang';
const assets = {
  hero: root + '/HERO WOMAN  BLACK SUIT.jpg', women: root + '/WOMEN COLLECTION.jpg', men: root + '/MEN COLLECTION.jpg', accessories: root + '/ACCESSORIES.jpg',
  blazer: root + '/BLAZER PRODUCT.jpg', dress: root + '/BLACK SATIN DRESS PRODUCT.jpg', shirt: root + '/TAILORED SHIRT.jpg', belt: root + '/LEATHER BELT.jpg',
  craft: root + '/CRAFTSMANSHIP PORTRAIT.jpg', tailoring: root + '/TAILORING DETAIL.jpg', fabric: root + '/FABRIC DETAIL.jpg', bag: root + '/LEATHER BAG.jpg',
  journal: root + '/FASHION JOURNAL PORTRAIT.jpg', behind: root + '/BEHIND THE COLLECTION.jpg', travel: root + '/TRAVEL JOURNAL.jpg', footer: root + '/FOOTER  BRAND IMAGE.jpg',
};

const collections = [
  ['Nữ', 'Xuân / Hè 2026', 'Nhẹ hơn.|Tự do hơn.', 'Những phom dáng chuyển động cùng cơ thể, để mỗi ngày đều có một khoảng thở riêng.', assets.women],
  ['Nam', 'Thu / Đông 2026', 'Sự hiện diện|không cần phô trương.', 'Tỷ lệ chuẩn xác, sắc độ sâu và những chi tiết chỉ dành cho người nhìn gần hơn.', assets.men],
  ['Phụ kiện', 'Tuyển chọn 2026', 'Đi cùng|một cá tính.', 'Những điểm chạm hoàn thiện một tổng thể theo cách thầm lặng nhất.', assets.accessories],
];
const products = [['Áo blazer cấu trúc', 'Nữ / May đo', '4.850.000 đ', assets.blazer], ['Váy satin đen', 'Nữ / Dạ tiệc', '3.680.000 đ', assets.dress], ['Sơ mi may đo', 'Nam / Essentials', '2.450.000 đ', assets.shirt], ['Thắt lưng da mảnh', 'Phụ kiện / Da thuộc', '1.280.000 đ', assets.belt]];

function ArrowLink({ children, href = '#bo-suu-tap' }) { return <a className="velas-arrow" href={href}>{children}<ArrowRight size={16} /></a>; }

function HomeModal({ close }) { return <div className="velas-modal" role="dialog" aria-modal="true" aria-labelledby="velas-home-title" onMouseDown={close}><div className="velas-home-modal" onMouseDown={(event) => event.stopPropagation()}><button type="button" aria-label="Đóng popup" onClick={close}><X size={19} /></button><p className="velas-kicker">Rời khỏi trải nghiệm</p><h2 id="velas-home-title">Quay lại trang chính?</h2><p>Bạn sẽ rời không gian VELAS và trở về portfolio.</p><div><button type="button" onClick={close}>Ở lại đây</button><a href="/">Về trang chính <ArrowRight size={16} /></a></div></div></div>; }

export function FashionExperience() {
  const [menuOpen, setMenuOpen] = useState(false); const [active, setActive] = useState(0); const [material, setMaterial] = useState('Lụa'); const [homeOpen, setHomeOpen] = useState(false); const [consultation, setConsultation] = useState(false);
  const current = collections[active];
  useEffect(() => { window.scrollTo(0, 0); document.title = 'VELAS - Mặc lên phong cách của bạn'; }, []);
  const openHome = () => setHomeOpen(true);
  return <main className="velas-page" id="dau-trang">
    <header className="velas-nav"><a className="velas-mark" href="#dau-trang">VELAS</a><nav className={menuOpen ? 'is-open' : ''} aria-label="Điều hướng VELAS">{[['Bộ sưu tập', '#bo-suu-tap'], ['Mới nhất', '#moi-nhat'], ['Chế tác', '#che-tac'], ['Editorial', '#editorial']].map(([label, href]) => <a href={href} key={href} onClick={() => setMenuOpen(false)}>{label}</a>)}<button type="button" className="velas-mobile-home" onClick={openHome}>Trang chính</button></nav><div className="velas-nav-actions"><button type="button" onClick={openHome}>Trang chính</button><a href="#bo-suu-tap">Khám phá</a><button className="velas-menu" type="button" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? 'Đóng menu' : 'Mở menu'}>{menuOpen ? <X /> : <Menu />}</button></div></header>
    <button type="button" className="velas-float-home" onClick={openHome} aria-label="Mở popup quay lại trang chính"><ArrowLeft size={17} /><span>Trang chính</span></button>
    <section className="velas-hero"><img src={assets.hero} alt="Người mẫu VELAS trong bộ suit đen" fetchPriority="high" /><div className="velas-hero-shade" /><div className="velas-hero-copy"><p>VELAS / Xuân Hè 2026</p><h1>Không chỉ là<br /><em>một bộ trang phục.</em></h1><span>Đó là cách bạn xuất hiện trong thế giới này.</span><div><a className="velas-solid" href="#bo-suu-tap">Khám phá bộ sưu tập <ArrowRight size={16} /></a><a className="velas-quiet-link" href="#editorial">Xem campaign</a></div></div><a className="velas-scroll" href="#tuyen-ngon">Cuộn để mở câu chuyện <i /></a><span className="velas-hero-number">01 / 06</span></section>
    <section className="velas-manifesto" id="tuyen-ngon"><p className="velas-kicker">Một cách hiện diện</p><h2>Ít hơn.<br /><em>Nhưng riêng hơn.</em></h2><p>VELAS tạo nên những thiết kế sống cùng nhịp điệu của bạn, không chạy theo một mùa và không cần lời giới thiệu quá lớn.</p><span>01</span></section>
    <section className="velas-collection" id="bo-suu-tap"><div className="velas-collection-head"><div><p className="velas-kicker">Bộ sưu tập</p><h2>Những thiết kế<br />để ở lại <em>lâu hơn một mùa.</em></h2></div><div className="velas-tabs" role="tablist">{collections.map(([label], index) => <button type="button" role="tab" aria-selected={active === index} className={active === index ? 'active' : ''} key={label} onClick={() => setActive(index)}>{label}</button>)}</div></div><div className="velas-collection-feature"><div className="velas-image-frame"><img src={current[4]} alt={'Bộ sưu tập ' + current[0] + ' VELAS'} loading="lazy" /></div><div className="velas-collection-copy"><span>{current[1]}</span><h3>{current[2].split('|').map((line) => <span key={line}>{line}</span>)}</h3><p>{current[3]}</p><ArrowLink>Khám phá</ArrowLink></div></div></section>
    <section className="velas-arrivals" id="moi-nhat"><div className="velas-arrival-intro"><p className="velas-kicker">Mới nhất</p><h2>Những thiết kế<br /><em>vừa xuất hiện.</em></h2><p>Những phom dáng mới được hoàn thiện từ chất liệu, ánh sáng và sự cân bằng của tỷ lệ.</p></div><div className="velas-product-grid">{products.map(([name, type, price, image], index) => <article key={name}><div className="velas-product-image"><img src={image} alt={name} loading="lazy" /><button type="button" aria-label={'Xem ' + name} onClick={() => setConsultation(true)}><Plus size={18} /></button></div><p>{type}</p><h3>{name}</h3><span>{price}</span><button type="button" className="velas-product-action" onClick={() => setConsultation(true)}>Xem chi tiết <ArrowRight size={14} /></button><i>0{index + 1}</i></article>)}</div></section>
    <section className="velas-craft" id="che-tac"><div className="velas-craft-photos"><img className="velas-craft-main" src={assets.craft} alt="Chân dung nghệ nhân trong xưởng VELAS" loading="lazy" /><img className="velas-craft-detail" src={assets.tailoring} alt="Chi tiết đường may VELAS" loading="lazy" /></div><div className="velas-craft-copy"><p className="velas-kicker">Được tạo ra với chủ đích</p><h2>Mỗi đường may.<br /><em>Một lý do.</em></h2><p>Mỗi chất liệu, mỗi tỷ lệ, mỗi điểm chạm đều được cân nhắc để tạo nên cảm giác đúng đắn khi bạn mặc lên người.</p><ArrowLink href="#chat-lieu">Nhìn gần hơn</ArrowLink></div></section>
    <section className="velas-materials" id="chat-lieu"><div><p className="velas-kicker">Chất liệu tạo nên cảm giác</p><h2>Mặc để<br /><em>cảm nhận.</em></h2><div className="velas-material-tabs">{['Lụa', 'Len', 'Linen', 'Da thuộc'].map((item) => <button type="button" key={item} className={material === item ? 'active' : ''} onClick={() => setMaterial(item)}>{item}</button>)}</div></div><div className="velas-material-image"><img src={material === 'Da thuộc' ? assets.bag : assets.fabric} alt={'Bề mặt chất liệu ' + material} loading="lazy" /><div><span>{material}</span><p>{material === 'Lụa' ? 'Mềm, mát và phản chiếu ánh sáng theo từng chuyển động.' : material === 'Len' ? 'Kết cấu ấm, sâu và giữ phom một cách tự nhiên.' : material === 'Linen' ? 'Thoáng, nhẹ và mang bề mặt có nhịp thở.' : 'Được hoàn thiện để trở nên đẹp hơn theo thời gian.'}</p><small>Thông tin demo</small></div></div></section>
    <section className="velas-editorial" id="editorial"><div className="velas-editorial-title"><p className="velas-kicker">Editorial</p><h2>Những câu chuyện<br />phía sau <em>những gì bạn mặc.</em></h2></div><div className="velas-editorial-grid"><article className="feature"><img src={assets.journal} alt="Editorial VELAS về nghệ thuật tối giản" loading="lazy" /><div><span>01 / Góc nhìn</span><h3>Nghệ thuật của sự tối giản</h3><ArrowLink href="#dau-trang">Đọc câu chuyện</ArrowLink></div></article><article><img src={assets.behind} alt="Hậu trường bộ sưu tập VELAS" loading="lazy" /><span>02 / Trong xưởng</span><h3>Khi chất liệu trở thành ngôn ngữ</h3></article><article><img src={assets.travel} alt="Nhật ký hành trình VELAS" loading="lazy" /><span>03 / Nhật ký</span><h3>Mặc cho chính mình</h3></article></div></section>
    <section className="velas-final"><img src={assets.footer} alt="Thế giới VELAS" loading="lazy" /><div><p className="velas-kicker">VELAS / 2026</p><h2>Mặc lên<br /><em>phong cách của bạn.</em></h2><button type="button" className="velas-solid" onClick={() => setConsultation(true)}>Tư vấn phong cách <ArrowRight size={16} /></button></div></section><footer className="velas-footer"><a href="#dau-trang" className="velas-mark">VELAS</a><p>Ít hơn. Nhưng tốt hơn.</p><div><a href="#bo-suu-tap">Bộ sưu tập</a><a href="#che-tac">Chế tác</a><a href="#editorial">Editorial</a></div><span>© 2026 VELAS. Dữ liệu demo.</span></footer>
    {homeOpen && <HomeModal close={() => setHomeOpen(false)} />}{consultation && <div className="velas-modal" role="dialog" aria-modal="true" aria-labelledby="velas-consult-title" onMouseDown={() => setConsultation(false)}><div className="velas-consult-modal" onMouseDown={(event) => event.stopPropagation()}><button type="button" aria-label="Đóng tư vấn" onClick={() => setConsultation(false)}><X size={19} /></button><p className="velas-kicker">Tư vấn phong cách</p><h2 id="velas-consult-title">Bạn đang tìm kiếm điều gì?</h2><div className="velas-consult-options">{['Đi làm', 'Dự tiệc', 'Hẹn hò', 'Du lịch', 'Hằng ngày'].map((item) => <button type="button" key={item} onClick={() => setConsultation(false)}>{item}</button>)}</div></div></div>}
  </main>;
}
