import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, CalendarDays, Check, ChevronDown, Compass, Globe2, Home, Menu, Play, Search, Sparkles, X } from 'lucide-react';
import './travel.css';

const assetRoot = '/assets/du-lich/';
const photos = ['ea19933b-e21b-4776-b524-c5fddb59851c','33a1f141-1317-4f37-b0fa-4e311c9153fc','3faf2095-994c-4dcf-8252-ea052315f1ed','4d3d85ae-b1e1-498b-81cc-2ef8012bd622','7516645d-d961-4640-b5bd-47b13f65b3f3','8511d748-5808-46a7-8ad8-134aadcb1ee6','890e13ce-f6bd-48bf-9695-4e6eccc1575e','aa861172-7333-4bbe-a44b-377fb57401b4'].map((id) => assetRoot + 'gpt-image-2_Premium_Vietnamese_domestic_travel_campaign_photography__Contemporary_luxury_tra-0_' + id + '.jpg');
const videos = [
  assetRoot + 'hailuo-2_3_Create_a_cinematic_hero_video_for_a_premium_Vietnamese_domestic_travel_website__-0_cd848dbd-efc1-4698-a6f3-d5d21175214a.mp4',
  assetRoot + 'hailuo-2_3_Create_a_cinematic_Vietnamese_domestic_travel_montage-style_video__ONE_CONTINUOU-0_b24acf0a-631f-4fb1-ab69-41c236337803.mp4',
];
const tourSeed = [
  ['Sapa — Fansipan','Miền Bắc','North','3N2Đ','2.590.000đ'], ['Hạ Long — Cát Bà','Miền Bắc','North','3N2Đ','3.490.000đ'],
  ['Ninh Bình — Tràng An','Miền Bắc','North','2N1Đ','1.890.000đ'], ['Đà Nẵng — Hội An','Miền Trung','Central','4N3Đ','3.990.000đ'],
  ['Phú Quốc','Miền Nam','South','3N2Đ','4.290.000đ'], ['Huế — Đà Nẵng','Miền Trung','Central','3N2Đ','2.990.000đ'],
  ['Đà Lạt','Miền Nam','South','3N2Đ','2.390.000đ'], ['Cần Thơ — Miền Tây','Miền Tây','Mekong','2N1Đ','1.790.000đ'],
];

const copy = {
  vi: { nav:['Điểm đến','Trải nghiệm','Tour trong nước','Cẩm nang','Ưu đãi'], consult:'Tư vấn miễn phí', heroTop:'Khám phá Việt Nam', hero:'Những hành trình', heroEm:'đáng trải nghiệm', heroSub:'Đi xa hơn để nhìn thấy Việt Nam theo một cách khác.', explore:'Khám phá hành trình', watch:'Xem phim hành trình', destination:'Điểm đến', destinationHint:'Bạn muốn khám phá đâu?', time:'Thời gian', experience:'Loại trải nghiệm', budget:'Ngân sách', find:'Tìm hành trình', all:'Tất cả', noResult:'Chưa tìm thấy hành trình phù hợp. Hãy thử lựa chọn khác.', details:'Xem hành trình', backTitle:'Quay về trang chính?', backCopy:'Bạn sẽ rời demo Du lịch và trở lại portfolio Một Người Một Studio.', stay:'Ở lại', goHome:'Về trang chính', successTitle:'Đã nhận yêu cầu', successCopy:'Cảm ơn bạn. Chuyên viên hành trình sẽ liên hệ trong thời gian sớm nhất.', close:'Đóng' },
  en: { nav:['Destinations','Experiences','Vietnam tours','Journal','Offers'], consult:'Free consultation', heroTop:'Discover Vietnam', hero:'Journeys worth', heroEm:'experiencing', heroSub:'Travel farther to see Vietnam from a different perspective.', explore:'Explore journeys', watch:'Watch the journey', destination:'Destination', destinationHint:'Where would you like to go?', time:'Duration', experience:'Experience', budget:'Budget', find:'Find a journey', all:'All', noResult:'No matching journey yet. Try another selection.', details:'View itinerary', backTitle:'Return to the main site?', backCopy:'You will leave the Travel demo and return to the Một Người Một Studio portfolio.', stay:'Stay here', goHome:'Go to main site', successTitle:'Request received', successCopy:'Thank you. A travel specialist will contact you shortly.', close:'Close' },
};

function ActionButton({ children, className = '', onClick, type = 'button' }) {
  return <button type={type} className={'travel-btn ' + className} onClick={onClick}>{children}</button>;
}

function TravelModal({ modal, onClose, lang }) {
  useEffect(() => {
    if (!modal) return undefined;
    const close = (event) => event.key === 'Escape' && onClose();
    document.body.style.overflow = 'hidden'; window.addEventListener('keydown', close);
    return () => { document.body.style.overflow = ''; window.removeEventListener('keydown', close); };
  }, [modal, onClose]);
  if (!modal) return null;
  if (modal.type === 'video') return <div className="travel-modal-backdrop" onMouseDown={onClose}><div className="travel-modal video-modal" role="dialog" aria-modal="true" aria-label="Travel video" onMouseDown={(e)=>e.stopPropagation()}><button className="modal-close" onClick={onClose} aria-label="Đóng"><X/></button><video autoPlay controls playsInline><source src={videos[1]} type="video/mp4"/></video></div></div>;
  return <div className="travel-modal-backdrop" onMouseDown={onClose}><div className="travel-modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" onMouseDown={(e)=>e.stopPropagation()}>
    <button className="modal-close" onClick={onClose} aria-label="Đóng"><X/></button>{modal.image && <img src={modal.image} alt=""/>}<div className="modal-copy"><p className="travel-eyebrow">{modal.kicker}</p><h2 id="modal-title">{modal.title}</h2><p>{modal.description}</p>{modal.facts && <div className="modal-facts">{modal.facts.map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div>}<div className="modal-actions"><a className="travel-btn primary" href="#consultation" onClick={onClose}>{lang === 'vi' ? 'Nhận tư vấn' : 'Get advice'} <ArrowRight size={16}/></a><ActionButton className="outline" onClick={onClose}>{copy[lang].close}</ActionButton></div></div>
  </div></div>;
}

function TravelNavigation({ open, setOpen, lang, setLang, onHome }) {
  const t = copy[lang]; const links = ['#destinations','#experiences','#tours','#journal','#offers'];
  return <header className={open ? 'travel-nav is-open' : 'travel-nav'}><button className="home-trigger" onClick={onHome} aria-label="Về trang chính"><ArrowLeft/><span>Portfolio</span></button><a className="travel-logo" href="#travel-top"><span>VỊNH</span><strong>VIỆT NAM</strong></a><nav>{t.nav.map((label,i)=><a key={links[i]} href={links[i]} onClick={()=>setOpen(false)}>{label}</a>)}</nav><div className="travel-nav-actions"><div className="language-switch" aria-label="Language"><Globe2/><button className={lang==='vi'?'active':''} onClick={()=>setLang('vi')}>VI</button><i/><button className={lang==='en'?'active':''} onClick={()=>setLang('en')}>EN</button></div><a href="#consultation">{t.consult}</a><button className="mobile-menu" aria-label={open?'Đóng menu':'Mở menu'} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header>;
}

export function TravelPage() {
  const [menuOpen,setMenuOpen]=useState(false); const [lang,setLang]=useState('vi'); const [region,setRegion]=useState('Tất cả'); const [query,setQuery]=useState(''); const [duration,setDuration]=useState(''); const [experience,setExperience]=useState(''); const [budget,setBudget]=useState(''); const [modal,setModal]=useState(null); const [homePopup,setHomePopup]=useState(false); const [submitted,setSubmitted]=useState(false);
  const t=copy[lang];
  useEffect(()=>{document.title=lang==='vi'?'Vịnh Việt Nam — Hành trình đáng trải nghiệm':'Vịnh Việt Nam — Journeys worth experiencing';},[lang]);
  const tours=useMemo(()=>tourSeed.map((tour,i)=>({name:tour[0],region:tour[1],regionEn:tour[2],duration:tour[3],price:tour[4],category:['nature','coast','culture','culture','coast','culture','nature','culture'][i],image:photos[(i+1)%photos.length],description:lang==='vi'?'Một hành trình cân bằng giữa cảnh quan, văn hóa bản địa và khoảng thời gian riêng để bạn thực sự cảm nhận điểm đến.':'A considered balance of landscape, local culture and unhurried time to truly experience the destination.'})),[lang]);
  const regionOptions=lang==='vi'?['Tất cả','Miền Bắc','Miền Trung','Miền Nam','Miền Tây']:['All','North','Central','South','Mekong'];
  const filteredTours=useMemo(()=>tours.filter((tour)=>{const regionMatch=region===t.all||tour.region===region||tour.regionEn===region; const durationMatch=!duration||tour.duration.startsWith(duration); const experienceMatch=!experience||tour.category===experience; const budgetNumber=Number(tour.price.replace(/\D/g,'')); const budgetMatch=!budget||(budget==='low'?budgetNumber<2500000:budget==='mid'?budgetNumber<4000000:budgetNumber>=4000000); return regionMatch&&durationMatch&&experienceMatch&&budgetMatch&&tour.name.toLowerCase().includes(query.toLowerCase());}),[tours,region,duration,experience,budget,query,t.all]);
  const openTour=(tour)=>setModal({type:'tour',kicker:tour.region,title:tour.name,description:tour.description,image:tour.image,facts:[[lang==='vi'?'Thời lượng':'Duration',tour.duration],[lang==='vi'?'Chi phí từ':'From',tour.price],[lang==='vi'?'Phong cách':'Style',experience|| (lang==='vi'?'Khám phá chậm':'Slow travel')]]});
  const runSearch=()=>window.requestAnimationFrame(()=>document.getElementById('tours')?.scrollIntoView({behavior:'smooth',block:'start'}));

  return <div className="travel-page" id="travel-top"><TravelNavigation open={menuOpen} setOpen={setMenuOpen} lang={lang} setLang={(next)=>{setLang(next);setRegion(next==='vi'?'Tất cả':'All');}} onHome={()=>setHomePopup(true)}/>
    <section className="travel-hero"><video autoPlay muted loop playsInline poster={photos[0]}><source src={videos[0]} type="video/mp4"/></video><div className="travel-hero-shade"/><div className="travel-hero-copy"><p className="travel-eyebrow">{t.heroTop}</p><h1>{t.hero}<br/><em>{t.heroEm}</em></h1><p>{t.heroSub}</p><div className="travel-actions"><a className="travel-btn primary" href="#tours">{t.explore}<ArrowRight size={16}/></a><ActionButton className="ghost" onClick={()=>setModal({type:'video'})}><Play size={15}/>{t.watch}</ActionButton></div></div><div className="hero-place"><span>21°01′N</span><strong>NINH BÌNH</strong><span>105°56′E</span></div><div className="hero-scroll">{lang==='vi'?'Cuộn để khám phá':'Scroll to discover'}<span/></div></section>

    <section className="journey-search" aria-label="Journey finder"><div><label>{t.destination}</label><div className="field-control"><Search size={16}/><input id="tour-query" value={query} onChange={(e)=>setQuery(e.target.value)} placeholder={t.destinationHint}/></div></div><div><label>{t.time}</label><div className="field-control"><CalendarDays size={16}/><select value={duration} onChange={(e)=>setDuration(e.target.value)}><option value="">{lang==='vi'?'Linh hoạt':'Flexible'}</option><option value="2">2 {lang==='vi'?'ngày':'days'}</option><option value="3">3 {lang==='vi'?'ngày':'days'}</option><option value="4">4 {lang==='vi'?'ngày':'days'}</option></select><ChevronDown size={14}/></div></div><div><label>{t.experience}</label><div className="field-control"><select value={experience} onChange={(e)=>setExperience(e.target.value)}><option value="">{lang==='vi'?'Mọi trải nghiệm':'All experiences'}</option><option value="coast">{lang==='vi'?'Biển và đảo':'Coast & island'}</option><option value="nature">{lang==='vi'?'Núi và thiên nhiên':'Mountains & nature'}</option><option value="culture">{lang==='vi'?'Văn hóa và ẩm thực':'Culture & cuisine'}</option></select><ChevronDown size={14}/></div></div><div><label>{t.budget}</label><div className="field-control"><select value={budget} onChange={(e)=>setBudget(e.target.value)}><option value="">{lang==='vi'?'Mọi ngân sách':'Any budget'}</option><option value="low">&lt; 2.500.000đ</option><option value="mid">2.500.000đ — 4.000.000đ</option><option value="high">4.000.000đ +</option></select><ChevronDown size={14}/></div></div><ActionButton className="search-submit" onClick={runSearch}>{t.find}<ArrowRight size={16}/></ActionButton></section>

    <section className="travel-section destinations" id="destinations"><div className="section-heading"><div><p className="travel-eyebrow">01 / {t.destination}</p><h2>{lang==='vi'?'Khám phá Việt Nam':'Discover Vietnam'}</h2></div><p>{lang==='vi'?'Mỗi vùng đất là một câu chuyện. Chọn nơi bạn muốn bắt đầu.':'Every region tells a story. Choose where yours begins.'}</p></div><div className="region-grid">{(lang==='vi'?['Miền Bắc','Miền Trung','Miền Nam','Miền Tây']:['North','Central','South','Mekong']).map((name,i)=><button className="region-tile" onClick={()=>{setRegion(name);runSearch();}} key={name} style={{backgroundImage:'url('+photos[i+1]+')'}}><span>0{i+1}</span><div><h3>{name}</h3><p>{(lang==='vi'?['Núi cao, ruộng bậc thang','Di sản và biển xanh','Đảo ngọc, nhịp sống nhiệt đới','Sông nước và miệt vườn']:['Highlands and rice terraces','Heritage and blue coast','Island life and tropical rhythm','Rivers and orchards'])[i]}</p><b>{lang==='vi'?'Khám phá':'Explore'}<ArrowRight size={14}/></b></div></button>)}</div></section>

    <section className="travel-section tour-section" id="tours"><div className="section-heading"><div><p className="travel-eyebrow">02 / {lang==='vi'?'Tour trong nước':'Vietnam tours'}</p><h2>{t.hero}<br/><em>{t.heroEm}</em></h2></div><p>{lang==='vi'?'Được thiết kế cho những người muốn khám phá Việt Nam theo cách của riêng mình.':'Designed for travellers who want to discover Vietnam in their own way.'}</p></div><div className="tour-tools"><div className="result-count"><strong>{String(filteredTours.length).padStart(2,'0')}</strong><span>{lang==='vi'?'hành trình phù hợp':'matching journeys'}</span></div><div className="region-filters">{regionOptions.map((item)=><button className={region===item?'active':''} onClick={()=>setRegion(item)} key={item}>{item}</button>)}</div></div>{filteredTours.length?<div className="tour-grid">{filteredTours.map((tour,i)=><article className="tour-card" key={tour.name} tabIndex="0" onClick={()=>openTour(tour)} onKeyDown={(e)=>e.key==='Enter'&&openTour(tour)}><div className="tour-image" style={{backgroundImage:'url('+tour.image+')'}}><span>0{i+1}</span><b>{lang==='vi'?tour.region:tour.regionEn}</b><div className="tour-hover"><span>{t.details}<ArrowRight size={15}/></span></div></div><div className="tour-meta"><h3>{tour.name}</h3><p>{tour.duration}<span>{lang==='vi'?'Từ':'From'} {tour.price}</span></p></div></article>)}</div>:<div className="empty-state"><Compass/><p>{t.noResult}</p><button onClick={()=>{setRegion(t.all);setDuration('');setBudget('');setQuery('');}}>{lang==='vi'?'Xóa bộ lọc':'Clear filters'}</button></div>}</section>

    <section className="travel-section experience-section" id="experiences"><div className="section-heading"><div><p className="travel-eyebrow">03 / {lang==='vi'?'Trải nghiệm':'Experiences'}</p><h2>{lang==='vi'?'Việt Nam':'Vietnam'}<br/><em>{lang==='vi'?'qua từng giác quan':'through every sense'}</em></h2></div><p>{lang==='vi'?'Chọn một khoảnh khắc bạn muốn mang về.':'Choose a moment you would like to bring home.'}</p></div><div className="experience-grid">{(lang==='vi'?[['Ẩm thực','Ăn một bữa cơm bên hiên nhà Hội An.'],['Bình minh','Đón bình minh trên biển Phú Quốc.'],['Núi rừng','Đi giữa ruộng bậc thang Mù Cang Chải.'],['Văn hóa','Ngồi thuyền giữa Tràng An.']]:[['Cuisine','Share a meal on a Hoi An veranda.'],['Sunrise','Welcome sunrise on Phu Quoc island.'],['Highlands','Walk through Mu Cang Chai terraces.'],['Culture','Drift by boat through Trang An.']]).map(([title,description],i)=><button onClick={()=>setModal({kicker:lang==='vi'?'Trải nghiệm Việt Nam':'Vietnam experience',title,description,image:photos[(i+4)%photos.length]})} key={title} style={{backgroundImage:'url('+photos[(i+4)%photos.length]+')'}}><div><span>0{i+1}</span><h3>{title}</h3><p>{description}</p><b>{lang==='vi'?'Xem trải nghiệm':'View experience'}<ArrowRight size={14}/></b></div></button>)}</div></section>

    <section className="why-section"><p className="travel-eyebrow">04 / {lang==='vi'?'Vì sao chọn chúng tôi':'Why travel with us'}</p><h2>{lang==='vi'?'Hành trình được chọn lọc,':'Considered journeys,'}<br/><em>{lang==='vi'?'tư vấn bằng sự thấu hiểu.':'advice shaped around you.'}</em></h2><div className="why-grid">{(lang==='vi'?[['Tour được chọn lọc','Hành trình xây dựng dựa trên trải nghiệm thực tế.'],['Lịch trình linh hoạt','Dễ điều chỉnh theo nhu cầu của bạn.'],['Tư vấn cá nhân','Đội ngũ hiểu điểm đến và mong muốn của bạn.'],['Minh bạch chi phí','Thông tin rõ ràng trước khi quyết định.']]:[['Curated journeys','Itineraries grounded in first-hand experience.'],['Flexible planning','Easy to adjust around your needs.'],['Personal advice','People who understand both you and the place.'],['Transparent cost','Clear information before any decision.']]).map(([title,description])=><article key={title}><Sparkles size={20}/><h3>{title}</h3><p>{description}</p></article>)}</div></section>

    <section className="travel-section journal-section" id="journal"><div className="section-heading"><div><p className="travel-eyebrow">05 / {lang==='vi'?'Cẩm nang lên đường':'Travel journal'}</p><h2>{lang==='vi'?'Đi rồi sẽ nhớ':'Stories to carry home'}</h2></div><button className="text-arrow" onClick={()=>setModal({kicker:'Travel journal',title:lang==='vi'?'Cẩm nang Việt Nam':'Vietnam travel journal',description:lang==='vi'?'Những ghi chép ngắn giúp bạn chọn đúng mùa, đi chậm hơn và hiểu sâu hơn về nơi mình đến.':'Short, useful notes to choose the right season, travel slower and understand every place more deeply.',image:photos[1]})}>{lang==='vi'?'Xem tất cả bài viết':'View all stories'}<ArrowRight size={15}/></button></div><div className="journal-grid">{(lang==='vi'?['Đi Sapa mùa nào đẹp nhất?','3 ngày ở Ninh Bình nên đi đâu?','Ăn gì khi đến Hội An?']:['When is Sapa at its best?','How to spend 3 days in Ninh Binh','What to eat in Hoi An']).map((title,i)=><article key={title} style={{backgroundImage:'url('+photos[(i+2)%photos.length]+')'}}><div><span>Travel notes / 0{i+1}</span><h3>{title}</h3><button onClick={()=>setModal({kicker:'Travel notes / 0'+(i+1),title,description:lang==='vi'?'Gợi ý được biên tập từ trải nghiệm địa phương, gồm thời điểm đẹp, nhịp đi phù hợp và những điều nhỏ không nên bỏ lỡ.':'An edited local guide covering the best time, a considered pace and small details worth noticing.',image:photos[(i+2)%photos.length]})}>{lang==='vi'?'Đọc bài':'Read story'}<ArrowRight size={14}/></button></div></article>)}</div></section>

    <section className="offer-section" id="offers"><div><p className="travel-eyebrow">{lang==='vi'?'Ưu đãi đang có':'Current offer'}</p><h2>{lang==='vi'?'Giảm đến':'Save up to'} <em>30%</em><br/>{lang==='vi'?'cho hành trình được chọn.':'on selected journeys.'}</h2></div><ActionButton className="light" onClick={()=>setModal({kicker:lang==='vi'?'Ưu đãi tháng này':'This month offer',title:lang==='vi'?'Chạm Việt Nam — ưu đãi 30%':'Touch Vietnam — save 30%',description:lang==='vi'?'Áp dụng cho một số ngày khởi hành Sapa, Đà Nẵng — Hội An và Phú Quốc. Số lượng giới hạn theo từng hành trình.':'Available on selected Sapa, Da Nang — Hoi An and Phu Quoc departures. Limited places on each journey.',image:photos[6],facts:[[lang==='vi'?'Thời hạn':'Valid until','30.09.2026'],[lang==='vi'?'Mức giảm':'Saving','Up to 30%']]})}>{lang==='vi'?'Xem ưu đãi':'View offer'}<ArrowRight size={16}/></ActionButton></section>

    <section className="consultation" id="consultation"><div><p className="travel-eyebrow">{lang==='vi'?'Hành trình tiếp theo':'Your next journey'}</p><h2>{lang==='vi'?'Chưa biết nên':'Not sure where'}<br/><em>{lang==='vi'?'đi đâu?':'to go?'}</em></h2><p>{lang==='vi'?'Hãy kể cho chúng tôi bạn muốn một chuyến đi như thế nào. Chúng tôi sẽ giúp bạn tìm hành trình phù hợp.':'Tell us how you would like your journey to feel. We will help you find the right itinerary.'}</p><div className="consult-steps"><span>01 · {lang==='vi'?'Chia sẻ mong muốn':'Share your ideas'}</span><span>02 · {lang==='vi'?'Nhận gợi ý riêng':'Receive tailored options'}</span><span>03 · {lang==='vi'?'Quyết định khi sẵn sàng':'Decide when ready'}</span></div></div>{submitted?<div className="success-card"><Check/><h3>{t.successTitle}</h3><p>{t.successCopy}</p><button onClick={()=>setSubmitted(false)}>{lang==='vi'?'Gửi yêu cầu khác':'Send another request'}</button></div>:<form onSubmit={(e)=>{e.preventDefault();setSubmitted(true);}}><label>{lang==='vi'?'Họ và tên':'Full name'}<input required autoComplete="name" placeholder={lang==='vi'?'Tên của bạn':'Your name'}/></label><label>{lang==='vi'?'Số điện thoại':'Phone number'}<input required type="tel" autoComplete="tel" pattern="[0-9 +()-]{8,}" placeholder="09xx xxx xxx"/></label><label>{lang==='vi'?'Bạn muốn trải nghiệm gì?':'What would you like to experience?'}<textarea rows="3" placeholder={lang==='vi'?'Biển, núi, ẩm thực...':'Coast, mountains, cuisine...'}/></label><button className="travel-btn primary" type="submit">{t.consult}<ArrowRight size={16}/></button></form>}</section>
    <footer className="travel-footer"><button className="footer-home" onClick={()=>setHomePopup(true)}><Home/> {lang==='vi'?'Trang portfolio':'Portfolio home'}</button><a className="travel-logo" href="#travel-top"><span>VỊNH</span><strong>VIỆT NAM</strong></a><p>Digital travel experience for Vietnam.</p><a href="#travel-top">{lang==='vi'?'Lên đầu trang ↑':'Back to top ↑'}</a></footer>
    {homePopup&&<div className="home-popup" role="dialog" aria-modal="true"><button className="popup-dismiss" onClick={()=>setHomePopup(false)} aria-label="Đóng"><X/></button><span><Home/></span><h2>{t.backTitle}</h2><p>{t.backCopy}</p><div><button onClick={()=>setHomePopup(false)}>{t.stay}</button><a href="/">{t.goHome}<ArrowRight size={15}/></a></div></div>}
    <TravelModal modal={modal} onClose={()=>setModal(null)} lang={lang}/>
  </div>;
}
